print('Hello World')
a = int(input('entre a :'))
b = int(input('entre b :'))
print("Arthematic Operators required in python")
print(a+b, '+ is the addition')
print(a-b , '- is the substration')
print(a/b, '/ is for division')
print(a%b, '% is for modules to find the reminder')
print(a*b , '* is for the multiply')
print(a**b, '** is for a^b a rase to power b')
print(a//b, '// stand for extracting the integer after division')