print('Relational Operators in Python')
a = int(input('Entre the value of a :'))
b = int(input('Entre the value of b :'))
print(a > b, '> a greater than b ')
print(a < b, '< a smaller than b ')
print(a >= b, '>= greater than or equal to')
print(a <= b, '<= smaller than or equal to')
print(a == b, '== camparison, did a equal to b')
print(a != b, '!= a not equal to b')