print('Bitwise Operator in Py')
a = int(1)
b = int(2)
print(a & b,'a & b AND both of them have to be 1 for 1 as output')
print(a | b,'a | b  OR one of them have to be 1 for 1 as output')
print(a ^ b,'a ^ b XOR 1^1 is 0, 1^0 is 1')
print(~ a, "~ a is NOT which mean 1 flips to 0 and 0 to 1")
print(a >> b, 'a >> b LEFT SHIFT is shift bits of a LEFT BY b')
print(a << b, 'a << b RIGHT SHIFT is shift bits of a RIGHT BY b')